# Generated by Django 3.1.3 on 2021-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VillageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_title', models.CharField(max_length=200)),
                ('vi_content', models.TextField()),
                ('vi_name', models.CharField(max_length=100)),
                ('vi_max', models.PositiveSmallIntegerField()),
                ('vi_selected', models.PositiveSmallIntegerField()),
                ('vi_create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
