# Generated by Django 3.1.3 on 2021-08-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honameuro', '0004_indivinfo_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indivinfo',
            name='max',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='indivinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indivinfo',
            name='selected',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indivinfo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='villageinfo',
            name='max',
            field=models.PositiveSmallIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='villageinfo',
            name='selected',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
