# Generated by Django 3.1.3 on 2021-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honameuro', '0005_auto_20210814_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indivinfo',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
