# Generated by Django 3.1.3 on 2021-08-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honameuro', '0006_auto_20210814_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indivinfo',
            name='topic',
        ),
        migrations.AlterField(
            model_name='villageinfo',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='villageinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='villageinfo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='생활', max_length=100, null=True)),
                ('indiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honameuro.indivinfo')),
            ],
        ),
    ]
