# Generated by Django 3.1.3 on 2021-08-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honameuro', '0008_remove_topic_indiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='indivinfo',
            name='topic',
            field=models.ForeignKey(default=1, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='honameuro.topic'),
        ),
    ]
